version: "3.3"
services:
  mongodb:
    image: mongo:latest
    container_name: mongol_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
